networks:
  oikono:
    name: oikono
  backend:
    name: backend
    external: true

services:
  oikono:
    container_name: oikono
    image: oikono:local
    build:
      context: .
      dockerfile: src/Oikono/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=oikono;Username=postgres;Password=postgres
      - Jwt__Key=ThisIsAVerySecureKeyForTesting123456789012345678901234567890
      - Jwt__Issuer=Oikono
      - Jwt__Audience=OikonoUsers
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341
    ports:
      - 8100:80
    networks:
      - oikono
      - backend
    restart: unless-stopped
